name: master-transporte

services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: mt_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - master-transporte-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2-alpine
    container_name: mt_redis
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --protected-mode no
      --maxmemory 512mb
      --maxmemory-policy volatile-lru
      --notify-keyspace-events Ex
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - master-transporte-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 5s
      retries: 30

  rabbitmq:
    image: rabbitmq:4.3.2-management
    container_name: mt_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin}
    ports:
      - "5672:5672" # porta AMQP (protocolo)
      - "15672:15672" # porta da interface web
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - master-transporte-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:alpine
    container_name: mt_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - rabbitmq
    networks:
      - master-transporte-network

networks:
  master-transporte-network:
    name: master-transporte-network
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
