export const ASAAS_WEBHOOK_EVENTS = {
  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  PAYMENT_OVERDUE: "PAYMENT_OVERDUE",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  PAYMENT_UPDATED: "PAYMENT_UPDATED",
} as const;

export type AsaasWebhookEventType = (typeof ASAAS_WEBHOOK_EVENTS)[keyof typeof ASAAS_WEBHOOK_EVENTS];
