export const ASAAS_WEBHOOK_EVENTS = {
  PAYMENT_CREATED: "PAYMENT_CREATED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  PAYMENT_OVERDUE: "PAYMENT_OVERDUE",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  PAYMENT_UPDATED: "PAYMENT_UPDATED",
  TRANSFER_DONE: "TRANSFER_DONE",
  TRANSFER_FAILED: "TRANSFER_FAILED",
  TRANSFER_CANCELLED: "TRANSFER_CANCELLED",
  TRANSFER_REFUNDED: "TRANSFER_REFUNDED",
} as const;

export type AsaasWebhookEventType = (typeof ASAAS_WEBHOOK_EVENTS)[keyof typeof ASAAS_WEBHOOK_EVENTS];
