export const MIN_PAYOUT_AMOUNT_CENTS = 1000;

export const CURRENCY = "BRL" as const;

export const ASAAS_WEBHOOK_EVENTS = {
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_OVERDUE: "PAYMENT_OVERDUE",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
} as const;
